baseURL: "https://mise-en-place.netlify.com/"
languageCode: "en-gb"
title: "Mise en Place"
theme: cookbook

menu:
    main:
      - identifier: recipes
        name: Recipes
        url: "/recipes/"
      - identifier: about
        name: About
        url: "/about/"
